### Block puzzle

The size (size) represents the number of blocks for the bredth, length and height

The (seq) sequence represents the sequence of the blocks.
A 0 means the next block goes straight:  
  
🔳 🔳 🔳  
  
while a 1 means it goes sideways like this:  
  
🔳 🔳  
🔳

<img src="/Users/dirkiemyburgh/Documents/Courses/Python for data science and machine learning/Block puzzle/unsolved.jpeg" alt="Unsolved Puzzle" width="300"/> <img src="/Users/dirkiemyburgh/Documents/Courses/Python for data science and machine learning/Block puzzle/solved.jpeg" alt="Solved Puzzle" width="300"/>

In [81]:
# Block specifications

size = 4
seq = '221121112211211211211111111121211111121221111221121111111111221'
seq = [int(x)-2 if x=='2' else int(1) for x in seq]
print(seq)
# size = 3
# seq = [0,0,1,1,0,1,1,0,1,1,0,1,1,0,1,1,0,1,1,0,1,1,0,1,1,0]
len(seq)

[0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1]


63

In [74]:
import numpy as np
import time

In [75]:
# Create the block
block = np.array([[[0]*size]*size]*size)

In [76]:
def list_possible_starts(sz):
    (sz+1)//2
    possible_starts = []
    for z in range((sz+1)//2):
        for y in range((sz+1)//2):
            for x in range((sz+1)//2):
                possible_starts.append([x,y,z])
    return possible_starts

In [77]:
# Functions
def new_pos(current_position, dir):
    new_pos = current_position.copy()
    if dir == 1: new_pos[0] += 1
    if dir == 2: new_pos[1] += 1
    if dir == 3: new_pos[2] += 1
    if dir == 4: new_pos[0] -= 1
    if dir == 5: new_pos[1] -= 1
    if dir == 6: new_pos[2] -= 1
    return new_pos

def valid_dir_if_not_straigt(directions):
    if directions[-1] == 0: valid_dir = [1,2,3,4,5,6]
    if directions[-1] == 1 or directions[-1] == 4: valid_dir = [2,3,5,6]
    if directions[-1] == 2 or directions[-1] == 5: valid_dir = [1,3,4,6]
    if directions[-1] == 3 or directions[-1] == 6: valid_dir = [1,2,4,5]
    return valid_dir

def valid_move(new_position, new_direction, seq_dir, directions):
    if len(directions) == 1 and sum([0 <= new_position[i] <= (size-1) for i in range(3)]) == 3:
        return True
        
    if seq_dir == 0 and new_direction != directions[-1]:
        return False
    
    valid_dir = valid_dir_if_not_straigt(directions)
    # print(new_direction, valid_dir)
    if seq_dir == 1 and new_direction not in valid_dir:
        return False

    if sum([0 <= new_position[i] <= (size-1) for i in range(3)]) == 3 and block[new_position[0],new_position[1],new_position[2]] == 0:
        return True
    else:
        return False

In [78]:
block = np.array([[[0]*size]*size]*size)
start_time = time.time()
c = 0
possible_starts = list_possible_starts(size)
while sum(sum(sum(block))) < size**3 and c < len(possible_starts):
    print_on = 1
    start = possible_starts[c]
    c += 1
    positions = [start]
    block[start[0],start[1],start[2]] = 1
    print("*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*")
    print("*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*")
    print("*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*")
    print(block)
    print("----------")
    directions = [6]
    new_direction = 1
    while (0 < len(directions) or new_direction < 7) and len(directions) < size**3:
        # print("directions:", directions, new_direction, "| positions:", positions)
        if round(time.time() - start_time,0)%10==0 and print_on:
            print(time.time() - start_time)
            print("directions:", directions, new_direction)
            print("positions filled:", len(directions)+1)
            print("----------")
            print_on = 0
        if round(time.time() - start_time,0)%10==1:
            print_on = 1    
        if new_direction < 7:
            new_position = new_pos(positions[-1], new_direction)
        if new_direction > 6:
            block[positions[-1][0],positions[-1][1],positions[-1][2]] = 0
            new_direction = directions[-1] + 1
            directions.pop()
            positions.pop()
        elif valid_move(new_position, new_direction, seq[len(directions)-1], directions):
            # print(new_position, new_direction)
            # print(seq)
            # print(len(directions), '-', seq[len(directions)-1])
            block[new_position[0],new_position[1],new_position[2]] = 1
            directions.append(new_direction)
            positions.append(new_position)
            new_direction = 1
            # print(round(time.time() - start_time,2), len(directions), len(positions))
            # print(" ")
            # print(block)
            # print("----------")
        else:
            new_direction += 1

if sum(sum(sum(block))) == size**3:
    print("PUZZLE WAS SOLVED<3<3<3")
    print(start)
    print(directions)
else:
    print("XXXX not solved!!!!! XXXX")
        

*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*
*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*
*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*----*
[[[1 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
----------
0.001683950424194336
directions: [6] 1
positions filled: 2
----------
9.500005006790161
directions: [6, 1, 1, 2, 3, 3, 1, 3, 4, 4, 4, 2, 1, 1, 6, 4, 4, 2, 6, 6, 1, 5, 1, 3, 1, 5, 6, 5, 3, 3, 4, 4, 2, 4, 6, 5, 1, 2, 2] 6
positions filled: 40
----------
19.50000309944153
directions: [6, 1, 1, 2, 3, 3, 1, 3, 4, 4, 4, 5, 6, 6, 1, 3, 3, 1, 6, 6, 1, 2, 6, 2, 3, 4, 6, 4, 3, 3, 1, 1, 2, 4, 3, 4, 5, 1, 1, 2] 5
positions filled: 

In [82]:
print('PUZZLE WAS SOLVED<3<3<3')
print([0, 0, 0])
print([6, 1, 1, 2, 4, 4, 3, 5, 1, 1, 1, 6, 2, 2, 4, 3, 3, 4, 6, 6, 4, 2, 1, 3, 1, 6, 1, 3, 5, 5, 4, 4, 3, 4, 2, 6, 2, 3, 3, 5, 5, 5, 6, 1, 3, 2, 2, 2, 6, 1, 1, 5, 3, 5, 6, 4, 5, 1, 3, 4, 2, 2, 2, 1])


PUZZLE WAS SOLVED<3<3<3
[0, 0, 0]
[6, 1, 1, 2, 4, 4, 3, 5, 1, 1, 1, 6, 2, 2, 4, 3, 3, 4, 6, 6, 4, 2, 1, 3, 1, 6, 1, 3, 5, 5, 4, 4, 3, 4, 2, 6, 2, 3, 3, 5, 5, 5, 6, 1, 3, 2, 2, 2, 6, 1, 1, 5, 3, 5, 6, 4, 5, 1, 3, 4, 2, 2, 2, 1]
